
<!-- Navbar -->
<nav class="navbar navbarmain">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li><a href="/admin/index/index">Accueil</a></li>
            <li><a href="/admin/landingpage/index">Articles Landingpage</a></li>
            <li><a href="/admin/partenaires/index">Partenaires</a></li>
            <li><a href="/admin/messages/index">Messages</a></li>
        </ul>
    </div>
</nav>
<!-- Fin navbar -->
<div class="container">
    <?= $message ?>

    <?php echo $this->form()->openTag($addForm); ?>
    <?php echo $this->formElement($addForm->get('titre')); ?>
    </br>
    <?php echo $this->formElement($addForm->get('contenu')); ?>
    </br>
    <?php echo $this->formElement($addForm->get('image')); ?>
    </br>
    <?php echo $this->formElement($addForm->get('submit')); ?>
    <?php echo $this->form()->closeTag(); ?>
</div>
