<!-- Navbar -->
<center><img src="../../img/bwlogo.png" alt="BeWeb Logo"></center>
<nav class="navbar navbarmain">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li><a href="/admin/index/index">Accueil</a></li>
            <li><a href="/admin/landingpage/index">Articles Landingpage</a></li>
            <li><a href="/admin/partenaires/index">Partenaires</a></li>
            <li><a href="/admin/messages/index">Messages</a></li>
        </ul>
    </div>
</nav>
<!-- Fin navbar -->

<div class="container">
    <?php
    echo $this->form()->openTag($articleForm);
    // echo $this->form()->addTag($articleForm);
    echo $this->formLabel($articleForm->get('titre'));
    echo $this->formElement($articleForm->get('titre'));
    //
    echo $this->formLabel($articleForm->get('image'));
    echo $this->formElement($articleForm->get('image'));
    echo $this->formLabel($articleForm->get('contenu'));
    echo $this->formElement($articleForm->get('contenu'));
    //
    echo $this->formElement($articleForm->get('submit'));
    echo $this->form()->closeTag();
    ?>
</div>
