<!-- Navbar -->
<nav class="navbar navbarmain">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li><a href="/admin/index/index">Accueil</a></li>
            <li><a href="/admin/landingpage/index">Articles Landingpage</a></li>
            <li><a href="/admin/partenaires/index">Partenaires</a></li>
            <li><a href="/admin/contacte/index">Messages</a></li>
        </ul>
    </div>
</nav>
<!-- Fin navbar -->
<br><br>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Contacte</h3>
    </div>
    <div class="panel-body">
        <table class="table">
            <?php foreach ($contacteListe as $contacte){
                echo '<tr>';
                echo '<td>'. $contacte->getId().'</td>';
                echo '<td>'. $contacte->getEmail().'</td>';
                echo '<td>'. $contacte->getObjet().'</td>';
                echo '<td>'. $contacte->getMessage().'</td>';
                echo '<td>'. $contacte->getDate().'</td>';
                echo '</br><td><a class="btn btn-danger" href="/admin/contacte/delete?id='.$contacte->getId().'">Supprimer</a></td></tr>';
                echo '</tr>';

                } ?>

            </table>
        </div>
    </div>
