<?php echo $this->doctype(); ?>
<html lang="fr">

<head>
	<title>BeWeb</title>
	<meta charset="UTF-8">
	<?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

	<!-- Le styles -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/main.css')
					->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
					->prependStylesheet($this->basePath() . '/css/bootstrap-slider.min.css')
					->prependStylesheet($this->basePath() . '/css/bootflat.min.css')
					->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

	<!-- Scripts -->
	<?php echo $this->headScript()
		->prependFile($this->basePath() . '/js/main.js')
		->prependFile($this->basePath() . '/js/bootstrap-slider.min.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery-3.1.1.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>
</head>
    <body>
        <header>
            <img src="/img/bwlogo.png" alt="BeWeb Logo">
        </header>
        <main>
            <?php echo $this->content; ?>
        </main>

        <footer>
            Copyright &copy; FondespierreRH
            <br><br><br><br>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
