<!-- Navbar -->
<nav class="navbar navbarmain">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li><a href="/admin/index/index">Accueil</a></li>
            <li><a href="/admin/landingpage/index">Articles Landingpage</a></li>
            <li><a href="/admin/partenaires/index">Partenaires</a></li>
            <li><a href="/admin/messages/index">Messages</a></li>
        </ul>
    </div>
</nav>
<!-- Fin navbar -->
<div class="container">
    <?php

     echo $this->form()->openTag($partenaireForm);
     echo $this->formElement($partenaireForm->get('titre'));
     echo $this->formElement($partenaireForm->get('image'));
     echo $this->formElement($partenaireForm->get('url'));
     echo $this->formElement($partenaireForm->get('submit'));
     echo $this->form()->closeTag();
      ?>
</div>
